export const AVAILABLE_INDICES = [
  { symbol: "OMXS30", name: "OMX Stockholm 30" },
  { symbol: "SPX", name: "S&P 500" },
  { symbol: "IXIC", name: "Nasdaq" },
  { symbol: "DJI", name: "Dow Jones" },
  { symbol: "SX5E", name: "Euro Stoxx 50" },
  { symbol: "DAX", name: "DAX" },
  { symbol: "FTSE", name: "FTSE 100" },
  { symbol: "CAC", name: "CAC 40" },
  { symbol: "N225", name: "Nikkei 225" },
  { symbol: "HSI", name: "Hang Seng" },
  { symbol: "SENSEX", name: "BSE Sensex" },
  { symbol: "KOSPI", name: "KOSPI" },
  { symbol: "OMXHPI", name: "OMX Helsinki" },
  { symbol: "OMXC25", name: "OMX Copenhagen 25" },
];

export const AVAILABLE_COMMODITIES = [
  { symbol: "GC", name: "Guld" },
  { symbol: "SI", name: "Silver" },
  { symbol: "PL", name: "Platina" },
  { symbol: "PA", name: "Palladium" },
  { symbol: "BRENT", name: "Olja Brent" },
  { symbol: "WTI", name: "Olja WTI" },
  { symbol: "NG", name: "Naturgas" },
  { symbol: "CU", name: "Koppar" },
  { symbol: "AL", name: "Aluminium" },
  { symbol: "WHEAT", name: "Vete" },
  { symbol: "CORN", name: "Majs" },
  { symbol: "SOY", name: "Sojabonor" },
  { symbol: "USD/SEK", name: "Dollarn" },
  { symbol: "EUR/SEK", name: "Euron" },
  { symbol: "GBP/SEK", name: "Pundet" },
];
