export const themes = {
  light: {
    bg: "#fff",
    bgSecondary: "#f8f9fd",
    bgCard: "#fff",
    text: "#131722",
    textSecondary: "#787b86",
    textMuted: "#b2b5be",
    border: "#e0e3eb",
    borderLight: "#f0f3fa",
    accent: "var(--brand)",
    accentLight: "#eef2ff",
    green: "var(--pos)",
    red: "var(--neg)",
    orange: "var(--warn)",
  },
  dark: {
    bg: "#0f1118",
    bgSecondary: "#1a1d29",
    bgCard: "#1e2130",
    text: "#e1e3e8",
    textSecondary: "#8b8fa3",
    textMuted: "#555971",
    border: "#2a2d3a",
    borderLight: "#1e2130",
    accent: "var(--green-400)",
    accentLight: "#1a2744",
    green: "var(--pos)",
    red: "var(--neg)",
    orange: "var(--warn)",
  },
};
